# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(640, 310)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(14, 22, 33); color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Expression = QtWidgets.QTextEdit(self.centralwidget)
        self.Expression.setGeometry(QtCore.QRect(10, 40, 311, 111))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Expression.setFont(font)
        self.Expression.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Expression.setStyleSheet("background-color: rgb(24, 37, 51);\n"
"color: rgb(255, 255, 255);")
        self.Expression.setObjectName("Expression")
        self.Number = QtWidgets.QTextEdit(self.centralwidget)
        self.Number.setGeometry(QtCore.QRect(10, 200, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Number.setFont(font)
        self.Number.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Number.setStyleSheet("background-color: rgb(24, 37, 51);\n"
"color: rgb(255, 255, 255);")
        self.Number.setObjectName("Number")
        self.Field = QtWidgets.QTextEdit(self.centralwidget)
        self.Field.setGeometry(QtCore.QRect(170, 200, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Field.setFont(font)
        self.Field.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Field.setStyleSheet("background-color: rgb(24, 37, 51);\n"
"color: rgb(255, 255, 255);")
        self.Field.setObjectName("Field")
        self.Answer = QtWidgets.QTextEdit(self.centralwidget)
        self.Answer.setGeometry(QtCore.QRect(340, 40, 281, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Answer.setFont(font)
        self.Answer.setStyleSheet("background-color: rgb(24, 37, 51);\n"
"color: rgb(255, 255, 255);")
        self.Answer.setReadOnly(True)
        self.Answer.setObjectName("Answer")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 170, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 170, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Enter = QtWidgets.QPushButton(self.centralwidget)
        self.Enter.setGeometry(QtCore.QRect(120, 260, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.Enter.setFont(font)
        self.Enter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Enter.setStyleSheet("background-color: rgb(24, 37, 51);\n"
"color: rgb(255, 255, 255);")
        self.Enter.setObjectName("Enter")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(340, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.label.setText(_translate("MainWindow", "Expression"))
        self.label_2.setText(_translate("MainWindow", "Number"))
        self.label_3.setText(_translate("MainWindow", "Field"))
        self.Enter.setText(_translate("MainWindow", "Enter"))
        self.label_4.setText(_translate("MainWindow", "Output"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
