# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(895, 502)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.ico"), QtGui.QIcon.Active, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(14, 22, 33);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEnter = QtWidgets.QTextEdit(self.centralwidget)
        self.textEnter.setGeometry(QtCore.QRect(10, 50, 351, 361))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.textEnter.setFont(font)
        self.textEnter.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textEnter.setStyleSheet("background-color: rgb(24, 37, 51);\n"
"color: rgb(255, 255, 255);")
        self.textEnter.setObjectName("textEnter")
        self.matrixH = QtWidgets.QRadioButton(self.centralwidget)
        self.matrixH.setGeometry(QtCore.QRect(140, 420, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.matrixH.setFont(font)
        self.matrixH.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.matrixH.setStyleSheet("color: rgb(255, 255, 255);")
        self.matrixH.setObjectName("matrixH")
        self.matrixG = QtWidgets.QRadioButton(self.centralwidget)
        self.matrixG.setGeometry(QtCore.QRect(14, 420, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.matrixG.setFont(font)
        self.matrixG.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.matrixG.setStyleSheet("color: rgb(255, 255, 255);")
        self.matrixG.setObjectName("matrixG")
        self.enter = QtWidgets.QPushButton(self.centralwidget)
        self.enter.setGeometry(QtCore.QRect(280, 420, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.enter.setFont(font)
        self.enter.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enter.setStyleSheet("background-color: rgb(24, 37, 51);\n"
"color: rgb(255, 255, 255);")
        self.enter.setObjectName("enter")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 460, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.textV = QtWidgets.QTextEdit(self.centralwidget)
        self.textV.setGeometry(QtCore.QRect(60, 460, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.textV.setFont(font)
        self.textV.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.textV.setStyleSheet("background-color: rgb(24, 37, 51);\n"
"color: rgb(255, 255, 255);")
        self.textV.setObjectName("textV")
        self.textOut = QtWidgets.QTextEdit(self.centralwidget)
        self.textOut.setGeometry(QtCore.QRect(380, 10, 501, 481))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(9)
        self.textOut.setFont(font)
        self.textOut.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.textOut.setStyleSheet("background-color: rgb(24, 37, 51);\n"
"color: rgb(255, 255, 255);")
        self.textOut.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textOut.setLineWrapColumnOrWidth(-4)
        self.textOut.setReadOnly(True)
        self.textOut.setObjectName("textOut")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LidCode"))
        self.matrixH.setText(_translate("MainWindow", "Verification"))
        self.matrixG.setText(_translate("MainWindow", "Generative"))
        self.enter.setText(_translate("MainWindow", "Enter"))
        self.label.setText(_translate("MainWindow", "V ="))
        self.label_2.setText(_translate("MainWindow", "Input field"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
